"""rollback

Revision ID: 1e96e55dcf05
Revises: 17491433675c
Create Date: 2024-05-30 13:41:00.754803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e96e55dcf05'
down_revision = '17491433675c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.ENUM('EXCELLENT', 'GOOD', 'SATISFACTORY', 'UNSATISFACTORY', 'POOR', 'TERRIBLE'),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=mysql.ENUM('EXCELLENT', 'GOOD', 'SATISFACTORY', 'UNSATISFACTORY', 'POOR', 'TERRIBLE'),
               existing_nullable=False)

    # ### end Alembic commands ###
